[package]
name = "fornix"
version = "0.1.0"
authors = [""]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [lib]
# path = "main/library.rs"

[[bin]]
name = "main"
path = "main/main.rs"

[dependencies]
druid = { git = "https://github.com/linebender/druid" }
