[package]
name = "fornix"
version = "0.1.0"
authors = [""]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "main/library.rs"
crate-type = ["cdylib"]

[[bin]]
name = "main"
path = "main/main.rs"

[dependencies]
serde_derive = "1.0.136"
serde_json = "1.0.79"
toml_edit = "0.13.4"
wasm-bindgen = "0.2"
