#!/usr/bin/env bash
    echo "project commands:"
    tree "$PROJECTR_COMMANDS_FOLDER/project" -C --dirsfirst  -A -F --noreport | sed 's/^/    /' | sed "1d"
    
    node -e 'try { Object.keys(require(process.env.PROJECTR_FOLDER+"/package.json").scripts).forEach(each=>console.log(`    npm run ${each}`))}catch(e){}'