#!/usr/bin/env bash

@ git/ignore "$PROJECTR_TEMPORARY_FOLDER/*"
@ git/ignore "!$PROJECTR_TEMPORARY_FOLDER/.keep"

settings/home/Library/Caches
# dont remove these next one unless you want passwords to be public
# these are redundant, but kept as a fail-safe
settings/home/Library/Keychains
settings/home/.gnupg
settings/home/.gnupg_pre_2.1
settings/home/.npmrc
settings/home/.vsce
settings/home/.gitconfig
settings/home/.mongorc.js
settings/home/.ungitrc
settings/home/.vuerc