#!/usr/bin/env bash
find "$1" -maxdepth 1 ! -path . -print0 2>/dev/null | sort -z | while read -d "$(printf '\0')" each
do
    # check if file exists
    if [ -f "$each" ]
    then
        source "$each"
    elif [ -d "$each" ]
    then
        # recursively source
        @ file_system/source_all "$each"
    fi
done