#!/usr/bin/env bash

# summary
#   this is a nuclear cleaning option 
#   - if its not part of the git repo
#   - and it will take a long time (>1min) to get the data back
#   => this command should get rid of it
#   useful when you're trying to reset a project back to 0 when debugging

# 
# confirm with the user
# 
read -p "Are you sure? (y/n)" -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    echo "canceling"
    exit 0
fi

# 
# first run the cleaning
# 
# clean all the small things
"$PROJECTR_COMMANDS_FOLDER/project/clean"

@ file_system/source_all "$PROJECTR_COMMANDS_FOLDER/#events/project/purge"