#!/usr/bin/env -S deno run --allow-all

import { Console, blue } from "https://deno.land/x/quickr@0.0.11/main/console.js"
import { FileSystem } from "https://deno.land/x/quickr@0.0.11/main/file_system.js"
import { Overwrite, run } from "https://deno.land/x/quickr@0.0.11/main/run.js"
import { createWorkspace } from "../../scripting_helpers/generate_workspace.js"

const projectRoot = Console.env.FORNIX_FOLDER||FileSystem.pwd
const projectSettings = JSON.parse(await FileSystem.read(`${projectRoot}/settings/project.json`))

// 
// create workspace
// 
const tauriSrc = await createWorkspace(projectSettings.workspaceFolder)
// var tauriSrc = `${projectRoot}/workspace.ignore/src-tauri`

// 
// install tauri
// 
await Deno.chdir(tauriSrc)
const { success } = await run('cargo', "install", "--path", ".").outcome

// 
// build the app!
// 
if (success) {
    // NOTE: not sure why MacOS and Linx are so different here
    if (Deno.build.os == "linux") {
        success && await run('cargo', "build")
        console.log(`\n   executable created in: ${blue`${Console.env.HOME}/.cargo/bin/`}`)
    } else if (Deno.build.os == "darwin") {
        await Deno.chdir(FileSystem.parentPath(tauriSrc))
        await run('cargo', "tauri", "build", "--verbose", ...Deno.args)
    }
}