#!/usr/bin/env bash

# main inputs
__temp_var__command_name="tools/java/check_java_modules"
# TODO: add java package manager here
# __temp_var__file_to_watch="$PROJECTR_FOLDER/requirements.txt" 
__temp_var__hash_check_name="pip_modules"
failed_check_command () {
    # what to do when node modules haven't been installed yet
    # TODO: install java packages here
    # if successful
    if [ $? -eq 0 ] 
    then
        echo "[$__temp_var__command_name] Check finished (dependencies installed)"
    # if failed
    else
        echo "[$__temp_var__command_name] Check failed: issues with install"
    fi
}

# ensure that the source file and hash file exist
echo 
echo "[$__temp_var__command_name] Checking"
if [ -f "$__temp_var__file_to_watch" ]; then
    # 
    # create check file
    # 
    __temp_var__location_of_hash="$PROJECTR_FOLDER/settings/.cache/.$__temp_var__hash_check_name.cleanable.hash"
    if ! [ -f "$__temp_var__location_of_hash" ]; then
        # make sure the folder exists
        mkdir -p "$(dirname "$__temp_var__location_of_hash")"
        touch "$__temp_var__location_of_hash"
    fi
    
    # 
    # compare check files
    # 
    __temp_var__old_hash="$(cat "$__temp_var__location_of_hash")"
    __temp_var__new_hash="$(cat "$__temp_var__file_to_watch" | md5sum)"
    # if something changed since last time; install!
    if [ "$__temp_var__old_hash" != "$__temp_var__new_hash" ]; then
        echo "$__temp_var__new_hash" > "$__temp_var__location_of_hash"
        failed_check_command
    else
        echo "[$__temp_var__command_name] Check Passed => assuming packages are installed"
    fi
    
    unset __temp_var__location_of_hash
    unset __temp_var__old_hash
    unset __temp_var__new_hash
else
    echo "[$__temp_var__command_name] Check Passed (but only because no dependency file was found)"
fi
unset __temp_var__command_name
unset __temp_var__file_to_watch
unset __temp_var__hash_check_name